config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]
  
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)

      respond_to do |format|
        if @kitten.save
          format.html { redirect_to @kitten, notice: "Kitten was successfully created." }
          format.json { render :show, status: :created, location: @kitten }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @kitten.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    respond_to do |format|
      if @kitten.update(event_params)
        format.html { redirect_to @kitten, notice: "Kitten was successfully updated." }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: "Kitten was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_form.html.erb
<%=form_with model: @kitten do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :age %>
  <%= f.number_field :cuteness %>
  <%= f.number_field :softness %>
  <%= f.submit%>

<% end %>

app/views/kittens/edit.html.erb
<h1> Edit Kitten </h1>

<%=render 'form', kitten: @kitten %>

<%= link_to 'Show', @kitten %>
<%= link_to 'Back', kittens_path %>
<%= link_to "Delete", @kitten, method: :delete, data: { confirm: "Are You Sure?" }%>  

app/views/kittens/index.html.erb
<h1> Kittens <h1>

<% @kittens.each do |k| %>
  <p><%= "Kitten Name: #{k.name}" %></p>
  <p><%= "Kitten Age: #{k.age}" %></p>
  <p><%= "Kitten Cuteness: #{k.cuteness}" %></p>
  <p><%= "Kitten Softness: #{k.softness}" %></p>
  <%= link_to "Delete", k, method: :delete, data: { confirm: "Are You Sure?" }%>  
<%end%>

app/views/kittens/new.html.erb
<h1> New Kitten </h1>

<%=render 'form', kitten: @kitten %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<p><%= "Kitten Name: #{@kitten.name}" %></p>
<p><%= "Kitten Age: #{@kitten.age}" %></p>
<p><%= "Kitten Cuteness: #{@kitten.cuteness}" %></p>
<p><%= "Kitten Softness: #{@kitten.softness}" %></p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>